version: "3.7"

services:
  dquiz_db_server:
    # 컨테이너 이름을 주고 싶다면 작성한다
    # container_name: test_database
    image: 4whomtbts/mysql:5.6
    environment:
      MYSQL_DATABASE: dquiz_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
